# Site settings
title: Sunnyyyyy
description: Jekyll Theme Test
# baseurl: "" # the subpath of your site, e.g. /blog
url: "lovysunny7.github.io.profile" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sunny**
user_description: I\'m a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. 
user_title: God of Software Engineer (Hope so)
email: lovysunny7@gmail.com
# twitter_username: lovysunny7
# github_username: lovysunny7
# gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
remote_theme : murraco/jekyll-theme-minimal-resume
